### ISSUE TITLE
Cannot upgrade from 1.0.0 to 1.0.3

### ISSUE THREAD

**Issue by robtaylo** [adobe-marketing-cloud-mobile/aemmobile#10]
Install aemm 1.0.0

Try this: npm update aemm
Then try this: aemm -v

Result:
Version 1.0.0

Expect:
Version 1.0.3

Now try this: sudo npm install -g aemm

Result: node_modules/aemm needs updating to 1.0.3 from 1.0.0 but we can't, as it's a symlink
request@2.33.0 node_modules/aemm/node_modules/connect-phonegap/node_modules/request -> node_modules/aemm/node_modules/connect-aemmobile/node_modules/request
shelljs@0.2.6 node_modules/aemm/node_modules/connect-phonegap/node_modules/shelljs -> node_modules/aemm/node_modules/connect-aemmobile/node_modules/shelljs
/usr/local/lib
└─┬ aemm@1.0.3
  └── connect-aemmobile@0.1.0  (git+https://github.com/adobe-marketing-cloud-mobile/connect-aemmobile.git#63648ed6b096bdc84c8768171e913b96d62d6853)

Try this: npm update -g aemm

Result: 

pm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g" "aemm"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at fs.js:1657:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robtaylo/aemmobile/npm-debug.log

**Comment by adzellman** [comment]
@robtaylo the npm entry is now public, can you verify that this now works for you?

**Comment by robtaylo** [comment]
it doesn't throw an error any more.
