### ISSUE TITLE
Install fails at async module

### ISSUE THREAD

**Issue by jasonsturges** [adobe-marketing-cloud-mobile/aemmobile#43]
Both methods of installation are failing.  Trying first:

    npm install -g aemm

And then, the alternate approach:

    git clone https://github.com/adobe-marketing-cloud-mobile/aemmobile.git
    cd aemmobile
    npm -g install
    npm link

Both fail (with `sudo`) when installing async:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules/.staging/async-78e744d0
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/async-78e744d0' -> '/usr/local/lib/node_modules/aemm/node_modules/localtunnel/node_modules/request/node_modules/form-data/node_modules/async'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/async-78e744d0' -> '/usr/local/lib/node_modules/aemm/node_modules/localtunnel/node_modules/request/node_modules/form-data/node_modules/async'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jsturges/Projects/aemmobile/npm-debug.log
npm ERR! code 1
```

This is with:
- node: v6.4.0
- npm: v3.10.3
- Mac OS X El Capitan v10.11.6

Any recommendations; or, fix in the pipeline?

**Comment by adzellman** [comment]
Looks like people have run into a similar issue with phonegap and cordova installs [here](https://github.com/npm/npm/issues/10995) and [here](https://github.com/npm/npm/issues/11265). Can you try running `npm cache clean` then try running `sudo npm install -g aemm`?

**Comment by jasonsturges** [comment]
@adzellman Thanks, I did try that; however, receive the same error.

**Comment by adzellman** [comment]
There is reference to it being a race condition in the installation. Some people report that running the cache clean and install over and over eventually works. E.g., one user reports that it took four tries. I don't wish this workflow upon our users, so I'll continue looking for a solution. In the meantime, if this is a blocking issue for you, then I would try this "lather-rinse-repeat" method.

**Comment by jasonsturges** [comment]
@adzellman Oh, thanks for that link.  While I had previously tried to clean cache, I guess I had to explicitly remove the former install:

```
sudo npm remove -g aemm
npm cache clean
sudo npm install -g aemm@latest
```

**Comment by adzellman** [comment]
Great! Perhaps we should add this to the README.
