### ISSUE TITLE
On Android, the app always starts in portrait mode

### ISSUE THREAD

**Issue by rhudea** [adobe-marketing-cloud-mobile/aemmobile#49]
On Android, there is no way to specify that you want the app to start in landscape.
I've tried using "aemm config --set screenOrientation landscape", but it was not working.

The solution I've found is to manually modify the file platforms/android/res/raw/application_settings.xml to change ScreenOrientation/Tablet to be landscape.

**Comment by HenryPing** [comment]
@adzellman 

This was introduced from your commit:
https://github.com/adobe-marketing-cloud-mobile/aemmobile/commit/a4dbf2bbdc64268b8bed45f52e3e2bf754cf640f

"aemm config --set screenOrientation landscape" fails to set the screenOrientation attribute in config.json. Looking at the code, it appears the same issue exists on iOS as well. Please take a look.
